/** */
export const REGISTER = 'REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const IS_REGISTERED_USER_UNDEFINED = 'IS_REGISTERED_USER_UNDEFINED';
export const IS_RESPONSE_MESSAGE_UNDEFINED = 'IS_RESPONSE_MESSAGE_UNDEFINED';
export const POST_SING_IN = 'POST_SING_IN';
export const POST_SING_IN_SUCCESS = 'POST_SING_IN_SUCCESS';
export const POST_SING_IN_REQUEST = 'POST_SING_IN_REQUEST';
export const POST_SING_IN_FAILURE = 'POST_SING_IN_FAILURE';

export const CLEAR_SIGN_IN_FINISHED = 'CLEAR_SIGN_IN_FINISHED';

export const PASWORD_RESET_LINK = 'PASWORD_RESET_LINK';
export const PASWORD_RESET_LINK_SUCCESS = 'PASWORD_RESET_LINK_SUCCESS';
export const PASWORD_RESET_LINK_REQUEST = 'PASWORD_RESET_LINK_REQUEST';
export const PASWORD_RESET_LINK_FAILURE = 'PASWORD_RESET_LINK_FAILURE';
export const CLEAR_PASSWORD_RESET_LINK = 'CLEAR_PASSWORD_RESET_LINK';

export const CONFIRM_EMPLOYEE_LINK = 'CONFIRM_EMPLOYEE_LINK';
export const CONFIRM_EMPLOYEE_LINK_SUCCESS = 'CONFIRM_EMPLOYEE_LINK_SUCCESS';
export const CONFIRM_EMPLOYEE_LINK_REQUEST = 'CONFIRM_EMPLOYEE_LINK_REQUEST';
export const CONFIRM_EMPLOYEE_LINK_FAILURE = 'CONFIRM_EMPLOYEE_LINK_FAILURE';
export const CONFIRM_EMPLOYEE_LINK_UNDEFINED = 'CONFIRM_EMPLOYEE_LINK_UNDEFINED';

export const PASSWORD_CHANGE = 'PASSWORD_CHANGE';
export const PASSWORD_CHANGE_SUCCESS = 'PASSWORD_CHANGE_SUCCESS';
export const PASSWORD_CHANGE_REQUEST = 'PASSWORD_CHANGE_REQUEST';
export const PASSWORD_CHANGE_FAILURE = 'PASSWORD_CHANGE_FAILURE';
export const CLEAR_PASSWORD_CHANGE = 'CLEAR_PASSWORD_CHANGE';

export const REGISTATION_FRIEND = 'REGISTATION_FRIEND';
export const REGISTATION_FRIEND_SUCCESS = 'REGISTATION_FRIEND_SUCCESS';
export const REGISTATION_FRIEND_REQUEST = 'REGISTATION_FRIEND_REQUEST';
export const REGISTATION_FRIEND_FAILURE = 'REGISTATION_FRIEND_FAILURE';
export const CLEAR_REGISTATION_FRIEND = 'CLEAR_REGISTATION_FRIEND';

export const SING_OUT = 'SING_OUT';
export const SING_OUT_SUCCESS = 'SING_OUT_SUCCESS';
export const SING_OUT_REQUEST = 'SING_OUT_REQUEST';
export const SING_OUT_FAILURE = 'SING_OUT_FAILURE';
export const GET_PROFILE_DATA = 'GET_PROFILE_DATA';

export const IS_CONFIRMED_EMAIL_AND_CODE = 'IS_CONFIRMED_EMAIL_AND_CODE';
export const SET_CONFIRMED_EMAIL_AND_CODE_UNDEFINED = 'SET_CONFIRMED_EMAIL_AND_CODE_UNDEFINED';

export const ACTIVE_TAB_IDENTIFICATION = 'ACTIVE_TAB_IDENTIFICATION';


//user reducer
export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE';




// passwordResetLink
// passwordChange
// logout
// register
// confirmEmpEmail
// confirmEmail

/*userReducer*/
export const TOOGLE_ACTIVE_PROFILE_CONTENT = 'TOOGLE_ACTIVE_PROFILE_CONTENT';
export const SHOW_EMAIL_CHECK_EMP_MODAL = 'SHOW_EMAIL_CHECK_EMP_MODAL';
export const TOOGLE_MENU = 'TOOGLE_MENU';
export const LG = 'LG';
export const IS_RESET_PASSWORD = 'IS_RESET_PASSWORD';